"""renamed_question_col

Revision ID: 5edfc6f73032
Revises: 8c3e4674cf39
Create Date: 2026-08-19 05:35:47.448245

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5edfc6f73032"
down_revision: Union[str, Sequence[str], None] = "8c3e4674cf39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exam_questions", sa.Column("image_asset_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        op.f("ix_exam_questions_image_asset_id"),
        "exam_questions",
        ["image_asset_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_exam_questions_image_asset_id_media_assets"),
        "exam_questions",
        "media_assets",
        ["image_asset_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("exam_questions", "image_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exam_questions",
        sa.Column(
            "image_url", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(
        op.f("fk_exam_questions_image_asset_id_media_assets"),
        "exam_questions",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_exam_questions_image_asset_id"), table_name="exam_questions")
    op.drop_column("exam_questions", "image_asset_id")
    # ### end Alembic commands ###
