"""add local media assets

Revision ID: 8c3e4674cf39
Revises: 0002_sync_v3_cutover
Create Date: 2026-08-19 04:35:18.466477

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c3e4674cf39"
down_revision: Union[str, Sequence[str], None] = "0002_sync_v3_cutover"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_assets",
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("created_by_actor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_actor_id"],
            ["local_actors.id"],
            name=op.f("fk_media_assets_created_by_actor_id_local_actors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
    )
    op.create_index(
        op.f("ix_media_assets_created_by_actor_id"),
        "media_assets",
        ["created_by_actor_id"],
        unique=False,
    )
    op.create_index(
        "ix_media_assets_mime_type_created",
        "media_assets",
        ["mime_type", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_assets_sha256"), "media_assets", ["sha256"], unique=False
    )
    op.create_index(
        op.f("ix_media_assets_storage_key"),
        "media_assets",
        ["storage_key"],
        unique=True,
    )
    op.add_column("questions", sa.Column("image_asset_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_questions_image_asset_id_media_assets"),
        "questions",
        "media_assets",
        ["image_asset_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("questions", "image_url")
    op.alter_column(
        "teacher_assignments",
        "effective_from",
        existing_type=sa.DATE(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "teacher_assignments",
        "effective_from",
        existing_type=sa.DATE(),
        server_default=sa.text("CURRENT_DATE"),
        existing_nullable=False,
    )
    op.add_column(
        "questions",
        sa.Column(
            "image_url", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(
        op.f("fk_questions_image_asset_id_media_assets"),
        "questions",
        type_="foreignkey",
    )
    op.drop_column("questions", "image_asset_id")
    op.drop_index(op.f("ix_media_assets_storage_key"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_sha256"), table_name="media_assets")
    op.drop_index("ix_media_assets_mime_type_created", table_name="media_assets")
    op.drop_index(
        op.f("ix_media_assets_created_by_actor_id"), table_name="media_assets"
    )
    op.drop_table("media_assets")
    # ### end Alembic commands ###
