"""Candidate models for Weave CBT."""

from __future__ import annotations

from datetime import datetime
from enum import Enum as PyEnum
from uuid import UUID

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    Enum as SQLEnum,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
    text as sql_text,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


ADMISSION_NUMBER_MAX_LENGTH = 128
NAME_MAX_LENGTH = 255
STATUS_REASON_MAX_LENGTH = 500
PIN_HASH_MAX_LENGTH = 512


# ========================== #
# ENUMS
# ========================== #


class CandidateStatus(str, PyEnum):
    """
    Eligibility state of a candidate on one examination roster.

    ELIGIBLE
        Candidate may participate in the examination subject to
        authentication and examination-start rules.

    BLOCKED
        Candidate remains on the roster but has been administratively
        prevented from entering the examination.

    WITHDRAWN
        Candidate is no longer academically eligible for the examination
        after roster reconciliation.

    Writing/submission state does NOT belong here. That is represented by
    ExamAttempt.
    """

    ELIGIBLE = "eligible"
    BLOCKED = "blocked"
    WITHDRAWN = "withdrawn"


# ========================== #
# EXAM CANDIDATE
# ========================== #


class ExamCandidate(Base):
    """
    Materialized examination-roster snapshot.

    ExamCandidate answers:

        "Is this student eligible to write this specific exam?"

    Candidate rows are generated by a background worker from synchronized
    academic eligibility after the examination has been sealed.

    They are NOT created individually by API requests.

    Identity fields such as admission number, display name, enrollment and
    class are snapshotted so an active examination does not depend on later
    mutations to synchronized academic projections.
    """

    __tablename__ = "exam_candidates"

    exam_id: Mapped[UUID] = mapped_column(
        ForeignKey(
            "exams.id",
            ondelete="RESTRICT",
        ),
        nullable=False,
        index=True,
    )

    enrollment_id: Mapped[UUID] = mapped_column(
        ForeignKey(
            "student_enrollments.id",
            ondelete="RESTRICT",
        ),
        nullable=False,
        index=True,
    )

    # Stable Weave student UUID.
    #
    # There is currently no separate local students table. Student identity
    # arrives through StudentEnrollment, so this UUID is intentionally stored
    # directly rather than pointing to an invented local FK.
    student_id: Mapped[UUID] = mapped_column(
        nullable=False,
        index=True,
    )

    class_id: Mapped[UUID] = mapped_column(
        ForeignKey(
            "academic_classes.id",
            ondelete="RESTRICT",
        ),
        nullable=False,
        index=True,
    )

    admission_number: Mapped[str] = mapped_column(
        String(ADMISSION_NUMBER_MAX_LENGTH),
        nullable=False,
        index=True,
    )

    display_name: Mapped[str] = mapped_column(
        String(NAME_MAX_LENGTH),
        nullable=False,
    )

    status: Mapped[CandidateStatus] = mapped_column(
        SQLEnum(
            CandidateStatus,
            name="candidate_status",
            native_enum=False,
            create_constraint=True,
            validate_strings=True,
            values_callable=lambda enum_cls: [item.value for item in enum_cls],
        ),
        nullable=False,
        default=CandidateStatus.ELIGIBLE,
        server_default=CandidateStatus.ELIGIBLE.value,
        index=True,
    )

    status_reason: Mapped[str | None] = mapped_column(
        String(STATUS_REASON_MAX_LENGTH),
        nullable=True,
    )

    # Which successful roster reconciliation produced or most recently
    # confirmed this candidate.
    roster_version: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=1,
        server_default=sql_text("1"),
        index=True,
    )

    __table_args__ = (
        UniqueConstraint(
            "exam_id",
            "enrollment_id",
            name="uq_exam_candidates_exam_enrollment",
        ),
        UniqueConstraint(
            "exam_id",
            "student_id",
            name="uq_exam_candidates_exam_student",
        ),
        UniqueConstraint(
            "exam_id",
            "admission_number",
            name="uq_exam_candidates_exam_admission_number",
        ),
        CheckConstraint(
            "roster_version >= 1",
            name="ck_exam_candidates_roster_version_positive",
        ),
        Index(
            "ix_exam_candidates_exam_status",
            "exam_id",
            "status",
        ),
        Index(
            "ix_exam_candidates_exam_class_status",
            "exam_id",
            "class_id",
            "status",
        ),
        Index(
            "ix_exam_candidates_exam_roster_version",
            "exam_id",
            "roster_version",
        ),
    )


# ========================== #
# STUDENT CBT CREDENTIAL
# ========================== #


class StudentCBTCredential(Base):
    """
    Local projection of a student's Weave-owned CBT credential.

    StudentCBTCredential answers:

        "Has this student supplied the correct CBT PIN?"

    It is NOT tied to one examination.

    Weave will eventually own:
        - PIN generation
        - tenant-scoped PIN uniqueness
        - secure PIN reveal
        - PIN rotation

    Local CBT receives only the verifier required for offline
    authentication.

    CBT must never store the plaintext PIN or Weave's encrypted
    revealable PIN value.
    """

    __tablename__ = "student_cbt_credentials"

    # Stable Weave student UUID.
    #
    # This intentionally has no ForeignKey because the current local academic
    # projection does not contain a standalone students table.
    student_id: Mapped[UUID] = mapped_column(
        nullable=False,
        unique=True,
        index=True,
    )

    pin_hash: Mapped[str] = mapped_column(
        String(PIN_HASH_MAX_LENGTH),
        nullable=False,
    )

    # Monotonically increasing Weave credential revision.
    #
    # Example:
    #
    # version 3 arrives locally
    # version 4 arrives -> replace version 3
    # delayed version 3 arrives -> ignore it
    credential_version: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=1,
        server_default=sql_text("1"),
    )

    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default=sql_text("true"),
        index=True,
    )

    # Timestamp supplied by Weave when the source credential was last
    # changed. Nullable for now because the Weave credential contract
    # has not yet been implemented.
    source_updated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # When this local server most recently applied the credential projection.
    synced_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    # Tombstone received from Weave.
    #
    # Projection rows are retained rather than physically removed so stale
    # synchronization events cannot accidentally resurrect old credentials.
    source_deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
    )

    __table_args__ = (
        CheckConstraint(
            "credential_version >= 1",
            name="ck_student_cbt_credentials_version_positive",
        ),
        CheckConstraint(
            "source_deleted_at IS NULL OR is_active = false",
            name="ck_student_cbt_credentials_deleted_inactive",
        ),
        Index(
            "ix_student_cbt_credentials_active_student",
            "student_id",
            "is_active",
        ),
    )


# ========================== #
# LATE START AUTHORIZATION
# ========================== #


class CandidateLateStartAuthorization(Base):
    """
    Durable administrative permission for one candidate to begin an exam
    after the normal start deadline.

    Example:

        latest_normal_start_at = 10:20
        candidate arrives       = 10:35

    The candidate may authenticate normally, but AttemptService must not
    allow Begin Exam unless a valid late-start authorization exists.

    The authorization is consumed when the candidate successfully begins
    the attempt.

    Historical rows remain stored for auditability.
    """

    __tablename__ = "candidate_late_start_authorizations"

    candidate_id: Mapped[UUID] = mapped_column(
        ForeignKey(
            "exam_candidates.id",
            ondelete="RESTRICT",
        ),
        nullable=False,
        index=True,
    )

    granted_by_actor_id: Mapped[UUID] = mapped_column(
        ForeignKey(
            "local_actors.id",
            ondelete="RESTRICT",
        ),
        nullable=False,
        index=True,
    )

    reason: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    granted_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        index=True,
    )

    # Optional expiry allows an admin to say:
    #
    # "This candidate may start late, but only within the next 10 minutes."
    expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # Set atomically when AttemptService uses this authorization to start
    # the candidate's examination.
    consumed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    revoked_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    revoked_by_actor_id: Mapped[UUID | None] = mapped_column(
        ForeignKey(
            "local_actors.id",
            ondelete="RESTRICT",
        ),
        nullable=True,
        index=True,
    )

    revocation_reason: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    __table_args__ = (
        CheckConstraint(
            "expires_at IS NULL OR expires_at >= granted_at",
            name="ck_candidate_late_start_expiry_valid",
        ),
        CheckConstraint(
            "consumed_at IS NULL OR consumed_at >= granted_at",
            name="ck_candidate_late_start_consumed_valid",
        ),
        CheckConstraint(
            "revoked_at IS NULL OR revoked_at >= granted_at",
            name="ck_candidate_late_start_revoked_valid",
        ),
        CheckConstraint(
            "revoked_at IS NULL OR revoked_by_actor_id IS NOT NULL",
            name="ck_candidate_late_start_revocation_actor_required",
        ),
        CheckConstraint(
            "revoked_at IS NULL OR revocation_reason IS NOT NULL",
            name="ck_candidate_late_start_revocation_reason_required",
        ),
        CheckConstraint(
            "NOT (consumed_at IS NOT NULL AND revoked_at IS NOT NULL)",
            name="ck_candidate_late_start_not_consumed_and_revoked",
        ),
        Index(
            "ix_candidate_late_start_candidate_granted",
            "candidate_id",
            "granted_at",
        ),
    )
